# Generated by Django 3.1.5 on 2021-03-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210117_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='is_stuff',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.usersprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_assistants', models.BooleanField(default=False)),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.specification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.usersprofile')),
            ],
        ),
    ]
