# Generated by Django 3.1.5 on 2021-03-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210329_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='doctors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
