# Generated by Django 3.1.5 on 2021-03-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210329_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
