# Generated by Django 3.1.5 on 2021-03-30 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 8, 28, 40, 736873)),
        ),
    ]
